services:
    _defaults:
        autowire: true
        bind:
            $ptsFileExtendedEntity: '%pts_file_extended_entity%'

    PlumTreeSystems\FileBundle\Service\UniversalFileManager:
        class: PlumTreeSystems\FileBundle\Service\UniversalFileManager
        public: true
        arguments:
            $fileProviderMap: '%pts_file_path_map%'
            $defaultProvider: '%pts_file_default_provider%'

    pts_file.security.manager:
        class: PlumTreeSystems\FileBundle\Security\SecurityManager
        public: true

    PlumTreeSystems\FileBundle\Security\SecurityManager:
        alias: pts_file.security.manager

    pts_file.security.provider.default:
        class: PlumTreeSystems\FileBundle\Security\DefaultFileSecurityProvider
        tags: [pts_file.security_provider]
        public: true
