PlumTreeSystems\FileBundle\Entity\File:
    type: mappedSuperclass
    table: pts_file
    fields:
        name:
            type: string
            length: 255
            unique: true
        context:
            type: string
            length: 255
        path:
            type: string
            length: 1000
        originalName:
            type: string
            length: 255
    lifecycleCallbacks: {  }
